GET http://localhost:3000/users

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Aditya Nugraha",
    "email": "aditya@gmail.com",
    "password": "12345678",
    "role": "user"
}

###
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "aditya@gmail.com",
    "password": "12345678"
}

###
POST http://localhost:3000/category
Content-Type: application/json

{
    "name": "Adaptor"
}

###
GET http://localhost:3000/category

###
DELETE http://localhost:3000/category/7 

###
POST http://localhost:3000/brand
Content-Type: application/json

{
    "name": "Robot"
}

###
GET http://localhost:3000/brand


###
GET http://localhost:3000/product

###
POST http://localhost:3000/product
Content-Type: application/json

{
    "name": "Vgen Cable Lightning",
    "categoryId": 1,
    "brandId": 2
}

###
PUT http://localhost:3000/product/4
Content-Type: application/json

{
    "stok": "tersedia"
}

###
GET http://localhost:3000/product/limit

###
POST http://localhost:3000/verify/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJpemtpLmlsaGFtaTMxQGdtYWlsLmNvbSIsImlhdCI6MTY4MzA0MDMzNn0.E0JJ4VPPyCc31hVZ1ZVxk60carOHi2A-EJYxsFg3zYw

###
GET http://localhost:3000/digiflazz

###
GET http://localhost:3000/digiflazz/prepaid

###
GET http://localhost:3000/pulsa

###
POST http://localhost:3000/pulsa
Content-Type: application/json

{
    "name": "SMARTFREN"
}

###
POST http://localhost:3000/productserver
Content-Type: application/json

{   
    "category": "E-Money"
}